### ISSUE TITLE
Formulario de registro V2.??

### ISSUE THREAD

**Issue by paocorrales** [MetaDocencia/inscripciones#1]
Abro esto para charlar sobre algunos detalles del formulario de registro.

**Comment by NPalopoli** [comment]
Van algunas opciones para preguntas y soluciones sobre limitaciones, principalmente de tecnología:

- Tengo una conexión a internet inestable o limitada
	+ Participar por llamada telefónica de Zoom,
	+ descargar antes y seguir la presentación en dispositivo propio,
	+ participar por escrito en documento de Google Docs (si es posible)

- No tengo internet
	+ Participar por llamada telefónica de Zoom, 
	+ descargar antes y seguir la presentación en dispositivo propio (si es posible)

- No tengo computadora, tablet, teléfono móvil, ni ningún otro dispoisitivo con el cual conectarme a internet / Tengo dispositivos para conectarme a internet, pero no andan bien
	+ Participar por llamada telefónica de Zoom
	
- No tengo micrófono
	+ Participar por escrito en chat de Zoom, 
	+  participar por escrito en documento de Google Docs
	
- Horarios incompatibles por trabajo o zona horaria
	+ Disponer de oferta de cursos en horario de mañana, tarde y noche

- Demanda familiar durante el curso
	+ Descargar y mirar la presentación antes,
	+ participar por escrito en documento de Google Docs cuando se convoque durante el curso

- Me conecto desde una tablet o teléfono móvil y no puedo hacer varias tareas con comodidad
	+ Descargar y mirar la presentación antes |  Participar por llamada telefónica de Zoom, 
	+ participar por escrito en documento de Google Docs

- No sé manejar Zoom con comodidad
	+ Mirar tutoriales oficiales de Zoom: https://support.zoom.us/hc/es/articles/206618765-Tutoriales-de-Zoom-en-video. Elegir el video sobre el tema deseado en la lista de videos disponibles. Ya reproduciendo el video, obtener subtítulos en español haciendo clic en la rueda de configuración abajo a la derecha en la ventana de Youtube, seleccionar “Subtítulos” y allí, “Español” (si no está disponible el idioma, seleccionar “Traducción Automática” y luego, “Español”). 

- No sé manejar Google Docs con comodidad
	+ Mirar antes el tutorial de MetaDocencia “Cómo crear y compartir un documento en Google Doc”: https://www.youtube.com/watch?v=UAZrqyOVTus

**Comment by paocorrales** [comment]
Mientras organizo mis ideas sobre las primeras opciones, pienso que las últimas dos opciones (zoom y docs) pueden volar porque ya preguntamos que experiencia tienen con esas herramientas en otra pregunta. Como el año pasado, esa información debería ser usada por le docente para prever cualquier problema y ayude a quien necesite.

No mandaría información/tutoriales previo al curso, creo que genera mucha ansiedad y no debería ser un requisito  saber usar zoom o docs para participar. Si piden información o sale el tema durante el curso, ya sabemos como manejarlo.

**Comment by NPalopoli** [comment]
Es cierto, puede parecer un requisito previo para hacer el curso y en verdad, no es esencial.

Yo recuerdo haber tenido gente en el Intro al ABC con alguna dificultad con Zoom o Docs. Seguro son muchas menos personas que antes las que lleguen a nuestros cursos con problemas así y los podremos manejar bien. Pero estas personas pueden quedar con la sensación de que es un limitanto o mejor, una herramienta que debería explorar para sus clases. Tener a mano links (o mejor, posts en nuestra web) a los que pueda dirigir el docente o ayudante durante el curso, simplificaría las cosas. Pero ya no es tema de formulario, claro!

**Comment by NPalopoli** [comment]
@

**Comment by paocorrales** [comment]
Dejo algunos comentarios luego de la reunión del core team.

Casi todas estas circunstancias podrías resolverse si permitimos que la persona **llame** por teléfono a zoom y se conecte de esa manera para escuchar mientras ve la clase desde otro dispositivo. Alternativamente podría seguir la presentación desde su dispositivo pasando las slides si se descarga la presentacion previamente. 

Podríamos activar esta opción e incluir la información necesaria en el mail de confirmación de calendly para todas las personas independientemente de si respondieron que si a esta pregunta. Esta manera de participar no es la ideal y por eso deberíamos mandar las instrucciones con un disclaimer super claro que indique que cosas podemos garantizar y cuales no si participan así. 

"Participar de manera escrita" implica que la persona no use el micrófono en ningun momento y participe usando el chat y el documento compartido en todas las instancias. Esto podemos detectarlo directamente cuando como docentes conocemos al grupo al que vamos enseñar. Tendriamos que dar las indicaciones adecuadas para que la persona sepa como participar (incluyendo las salas de trabajo). 

Con todo lo anterior cubrimos las necesidades tecnológicas sin necesidad de generar un proceso específico que implique analizar caso por caso.

**Comment by paocorrales** [comment]
Los posibles cambios para la versión 2.1 o 2? quedaron para el futuro.
