### ISSUE TITLE
Nuevo sistema de inscripciones

### ISSUE THREAD

**Issue by paocorrales** [MetaDocencia/inscripciones#2]
Necesitamos un sistema de inscripciones que:

- permita a las personas participar en más de un curso
- tenga en cuenta correlatividad entre cursos
- eventualmente también nos permita registrar la participación
- sea compatible con lo que ya tenemos

**Comment by NPalopoli** [comment]
Una observación para el Coordinadore de curso: como se suma gente por fuera del core-team a ser Docente de cursos, hay que darles acceso a la carpeta del curso con antelación. Además deberían poder loguearse a la cuenta de Zoom.

**Comment by paocorrales** [comment]
Desde la cuenta ayuda.metadocencia@gmail.com cualquiera puede tener acceso a la carpeta de materiales donde están las carpetas de cada curso. 

Pero nos falta resolver lo de compartir el link a zoom definitivamente. Si les invitamos al evento desde google calendar, cada vez que alguien se inscribe el evento se actualiza y les llega un mail, es muy molesto. Podemos ver de cambiar la configuración o pensar en otra cosa. 

Y respecto de loguearse en zoom es otro gran tema. Capaz se puede configurar la cuenta para que al entrar ayudante/docente pueda reclamar host?
